### Get all tasks

GET http://localhost:8081/api/tasks

### Create new task

PUT http://localhost:8081/api/tasks/1
Content-Type: application/json
#Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Created test task 1",
  "description": "Description 1.",
  "startDate": "2024-02-01 08:00",
  "endDate": "2024-02-01 12:00"
}
